### ISSUE TITLE
Traceback on start

### ISSUE THREAD

**Issue by datamuc** [shashi/shellsparrow#1]
<pre>
danielt@lion:..hellsparrow> ./shsd 
creating client...
Traceback (most recent call last):
  File "./shsd", line 266, in <module>
    logIn()
  File "./shsd", line 215, in logIn
    c=Client(JID(p.get(PN,"jid")) ,p.get(PN,"password"))
  File "/var/lib/python-support/python2.6/pyxmpp/jid.py", line 95, in __new__
    obj.__from_unicode(node_or_jid)
  File "/var/lib/python-support/python2.6/pyxmpp/jid.py", line 140, in __from_unicode
    self.__set_resource(s1[1])
  File "/var/lib/python-support/python2.6/pyxmpp/jid.py", line 196, in __set_resource
    s=resourceprep.prepare(s)
  File "/var/lib/python-support/python2.6/pyxmpp/xmppstringprep.py", line 157, in prepare
    s=self.prohibit(s)
  File "/var/lib/python-support/python2.6/pyxmpp/xmppstringprep.py", line 217, in prohibit
    raise StringprepError,"Prohibited character: %r" % (c,)
pyxmpp.xmppstringprep.StringprepError: Prohibited character: u'\t'
</pre>

**Comment by datamuc** [comment]
Ah, it works if i remove the comments of the sample config
